from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import Any

from app.ai.context_hash import generate_context_hash
from app.database.ai_report_repository import AIReportRepository


DEFAULT_REPORT_TYPE = "national"
DEFAULT_CONTEXT_VERSION = "1.0.0"


class NationalReportServiceError(RuntimeError):
    """
    Raised when the national report workflow cannot be started.
    """


class InvalidAnalysisContextError(ValueError):
    """
    Raised when the supplied analytics context is invalid.
    """


@dataclass(frozen=True, slots=True)
class AnalysisRunResult:
    """
    Result returned after a national analysis run is created.

    This object does not contain an AI report yet. It only represents
    the initialized analysis workflow and its persisted context.
    """

    analysis_run_id: int
    report_type: str
    analysis_date: date
    context_version: str
    context_hash: str
    status: str

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the result into a JSON-safe dictionary.
        """

        return {
            "analysis_run_id": self.analysis_run_id,
            "report_type": self.report_type,
            "analysis_date": self.analysis_date.isoformat(),
            "context_version": self.context_version,
            "context_hash": self.context_hash,
            "status": self.status,
        }


class NationalReportService:
    """
    Orchestrates the national food-price analysis workflow.

    Step 10 responsibilities:

    1. Validate the prepared analytics context.
    2. Resolve the context version.
    3. Generate a deterministic context hash.
    4. Create an analysis run in PostgreSQL.
    5. Return structured analysis-run metadata.

    OpenAI generation and report-version persistence will be added
    in the following step.
    """

    def __init__(
        self,
        repository: AIReportRepository,
    ) -> None:
        self.repository = repository

    def start_analysis(
        self,
        *,
        analytics_context: dict[str, Any],
        analysis_date: date | None = None,
        report_type: str = DEFAULT_REPORT_TYPE,
    ) -> AnalysisRunResult:
        """
        Initialize and persist a national analysis run.

        Args:
            analytics_context:
                Prepared JSON-safe context generated by Context Builder.

            analysis_date:
                Logical date of the analysis. Defaults to today's date.

            report_type:
                Report category stored in ai_analysis_runs.

        Returns:
            AnalysisRunResult containing the new database ID, hash,
            context version, date, and current status.
        """

        self._validate_context(analytics_context)
        normalized_report_type = self._normalize_report_type(report_type)

        selected_analysis_date = analysis_date or date.today()

        context_version = self._resolve_context_version(
            analytics_context,
        )

        context_hash = generate_context_hash(
            analytics_context,
        )

        try:
            analysis_run_id = self.repository.create_analysis_run(
                report_type=normalized_report_type,
                analysis_date=selected_analysis_date,
                context_version=context_version,
                context_hash=context_hash,
                context_json=analytics_context,
            )
        except Exception as exc:
            raise NationalReportServiceError(
                "Gagal membuat national analysis run."
            ) from exc

        return AnalysisRunResult(
            analysis_run_id=analysis_run_id,
            report_type=normalized_report_type,
            analysis_date=selected_analysis_date,
            context_version=context_version,
            context_hash=context_hash,
            status="PROCESSING",
        )

    @staticmethod
    def _validate_context(
        analytics_context: dict[str, Any],
    ) -> None:
        """
        Validate the minimum structure required by the service.
        """

        if not isinstance(analytics_context, dict):
            raise InvalidAnalysisContextError(
                "analytics_context harus berupa dictionary."
            )

        if not analytics_context:
            raise InvalidAnalysisContextError(
                "analytics_context tidak boleh kosong."
            )

        context_metadata = analytics_context.get(
            "context_metadata",
        )

        if not isinstance(context_metadata, dict):
            raise InvalidAnalysisContextError(
                "analytics_context harus memiliki "
                "'context_metadata' berupa dictionary."
            )

        context_version = context_metadata.get(
            "context_version",
        )

        if context_version is not None:
            if not isinstance(context_version, str):
                raise InvalidAnalysisContextError(
                    "context_metadata.context_version "
                    "harus berupa string."
                )

            if not context_version.strip():
                raise InvalidAnalysisContextError(
                    "context_metadata.context_version "
                    "tidak boleh berupa string kosong."
                )

    @staticmethod
    def _resolve_context_version(
        analytics_context: dict[str, Any],
    ) -> str:
        """
        Resolve the context version from metadata.

        Version 1.0.0 is used as a safe default while maintaining
        backward compatibility with older prepared contexts.
        """

        context_metadata = analytics_context[
            "context_metadata"
        ]

        raw_version = context_metadata.get(
            "context_version",
            DEFAULT_CONTEXT_VERSION,
        )

        return str(raw_version).strip()

    @staticmethod
    def _normalize_report_type(
        report_type: str,
    ) -> str:
        """
        Validate and normalize the report type.
        """

        if not isinstance(report_type, str):
            raise ValueError(
                "report_type harus berupa string."
            )

        normalized = report_type.strip().lower()

        if not normalized:
            raise ValueError(
                "report_type tidak boleh kosong."
            )

        return normalized